<!-- packages/smart-dev/datatable-storer/src/resources/views/components/visibility-modal.blade.php -->
<div class="modal fade" id="modal-datatable-visibility" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Column Visibility</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="datatable-column-switches">
                <!-- Switches generated by JS -->
            </div>
        </div>
    </div>
</div>